### ISSUE TITLE
Shin Megami Tensei V: Vengeance

### ISSUE THREAD

**Issue by SomaIsBatman** [AnimatedSwine37/UnrealEssentials#12]
Unable to find Unreal version number.
If it's a problem on my end, i'd appreciate some pointers, if not, could you add support to it?

**Comment by AnimatedSwine37** [comment]
Unless an update has changed something it should work fine. 
Can you check that you're using the shipping exe. There are probably two, one in the game's root folder and then another in Content/Binaries/Win64 which has -shipping in the name, you need to use that one (I'm not at my PC so the path I just said might be slightly off but hopefully you can find it)

**Comment by SomaIsBatman** [comment]
Oh yeah, that did it for me. Reloaded II used the root folder automatically, changing to the shipping exe worked. Thanks a lot man.
