### ISSUE TITLE
Does not recognise The Callisto Protocol

### ISSUE THREAD

**Issue by KingZ98** [AnimatedSwine37/UnrealEssentials#15]
Hi all,

Just wanted to let you know that Unreal Essentials doesn't recognise The Callisto Protocol as a Unreal game and due to the fact that the ToC Patcher seems to crash now whenever you try to load in custom models and doesn't appear to be getting updates this might be the only way for the game to continue to be modable on none Steam platforms. If possible could you please add support?

**Comment by AnimatedSwine37** [comment]
I've added support with version 1.1.5 of Unreal Essentials. 
Note that you'll need to either use ASI loader (Edit Application->Advanced Tools & Options->Deploy ASI Loader in Reloaded) or remove the Steam DRM on the game with [Steamless](https://github.com/atom0s/Steamless/) for it to work.

Let me know how it goes.

**Comment by KingZ98** [comment]
It works thank you so much, can finally use a custom model
